import type { Metadata } from "next";
import "../globals.css";
import EmployeeHeader from "../components/employeeHeader";

import RootLayout from "@/app/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// http://localhost:3000/employee/home

export default async function HeaderOnlyLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <RootLayout>
        <EmployeeHeader />
        {children}
    </RootLayout>
  );
}
